version: "3"

services:
  redis:
    env_file:
      - ".env"
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  worker:
    build:
      context: "."
    command: celery -A make_celery worker -l info
    depends_on:
      - "redis"
    env_file:
      - ".env"

  web:
    container_name: vkcc-auto
    build:
      context: "."
    depends_on:
      - "worker"
    env_file:
      - ".env"
    ports:
      - "8000:8000"

volumes:
  redis: {}